/*
 * CloudServerWindow.java
 *
 * Created on __DATE__, __TIME__
 */

package com.mona.cloudserver;

import org.springframework.beans.factory.BeanFactory;

import com.mona.dao.DataBaseDataSource;
import com.mona.dao.RegistrationDAO;


/**
 *
 * @author  __USER__
 */
public class CloudServerWindow extends javax.swing.JFrame {
	RegistrationDAO registrationDAO;

	BeanFactory factory;
	/** Creates new form CloudServerWindow */
	public CloudServerWindow() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		BeanFactory factory = new DataBaseDataSource().getDataFactory();
		registrationDAO = (RegistrationDAO) factory.getBean("registrationDAO");
		
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("CloudServerWindow");

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
		jLabel1.setForeground(new java.awt.Color(255, 0, 0));
		jLabel1.setText("Cloud Server Uploaded Files");

		Object obj[][] = registrationDAO.viewCloudFiles();
		Object string[] = registrationDAO.viewCloudMetaData();
		jTable1.setModel(new javax.swing.table.DefaultTableModel(obj, string));
		jScrollPane1.setViewportView(jTable1);

		


		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(335, 335, 335)
						.addComponent(jLabel1).addContainerGap(286,
								Short.MAX_VALUE)).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(18,
						Short.MAX_VALUE).addComponent(jScrollPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 909,
						javax.swing.GroupLayout.PREFERRED_SIZE).addGap(27, 27,
						27)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addGap(38, 38, 38).addComponent(
						jLabel1).addGap(18, 18, 18).addComponent(jScrollPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(104, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CloudServerWindow().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}