/*
 * GroupManagerForm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.mona.user;

import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;

import org.springframework.beans.factory.BeanFactory;

import com.mona.dao.DataBaseDataSource;
import com.mona.dao.RegistrationDAO;
import com.mona.group.FileSystemModel;

/**
 * 
 * @author __USER__
 */
public class GroupManagerForm extends javax.swing.JFrame {
	private FileSystemModel fileSystemModel;
	RegistrationDAO registrationDAO;
	Users users;
	BeanFactory factory;
	ArrayList<Users> groupchangerequest;

	/** Creates new form GroupManagerForm */
	public GroupManagerForm(ArrayList<Users> groupchangerequest) {
		this.groupchangerequest = groupchangerequest;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		BeanFactory factory = new DataBaseDataSource().getDataFactory();
		registrationDAO = (RegistrationDAO) factory.getBean("registrationDAO");

		jScrollPane1 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox();
		jButton4 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("GroupManagerWindow");
		setBackground(new java.awt.Color(255, 153, 153));
		setForeground(new java.awt.Color(153, 153, 255));

		jScrollPane1.setViewportView(jTree1);

		Object obj[][] = registrationDAO.viewAllCloudUsers();
		Object string[] = registrationDAO.viewUserLoginMetaData();
		jTable1.setModel(new javax.swing.table.DefaultTableModel(obj, string));
		jScrollPane2.setViewportView(jTable1);

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "UserId",
						"OldGroupName", "NewGroupName", "RequestDate" }));
		jScrollPane3.setViewportView(jTable2);

		jButton1.setText("View Groups");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("ViewChangeGroupRequest");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("ViewAllUsers");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
				registrationDAO.viewGroups().split(",")));

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel1.setForeground(new java.awt.Color(255, 0, 51));
		jLabel1.setText("Groups :");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
		jLabel2.setForeground(new java.awt.Color(255, 0, 102));
		jLabel2.setText("Users :");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(
				registrationDAO.viewUserNames().split(",")));

		jButton4.setText("ChangeGroup");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												236,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				175,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jButton1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								175,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton2,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								175,
																								Short.MAX_VALUE)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGap(
																				10,
																				10,
																				10)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel1))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jComboBox2,
																								0,
																								102,
																								Short.MAX_VALUE)
																						.addComponent(
																								jComboBox1,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								0,
																								102,
																								Short.MAX_VALUE)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGap(
																				52,
																				52,
																				52)
																		.addComponent(
																				jButton4)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												406,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addComponent(jScrollPane2,
								javax.swing.GroupLayout.DEFAULT_SIZE, 829,
								Short.MAX_VALUE));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																361,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																361,
																Short.MAX_VALUE)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGap(
																				20,
																				20,
																				20)
																		.addComponent(
																				jButton1)
																		.addGap(
																				26,
																				26,
																				26)
																		.addComponent(
																				jButton2)
																		.addGap(
																				39,
																				39,
																				39)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jComboBox1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				27,
																				27,
																				27)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jComboBox2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				34,
																				34,
																				34)
																		.addComponent(
																				jButton4)
																		.addGap(
																				41,
																				41,
																				41)
																		.addComponent(
																				jButton3)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												256,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		Object obj[][] = registrationDAO.viewAllCloudUsers();
		Object string[] = registrationDAO.viewUserLoginMetaData();
		jTable1.setModel(new javax.swing.table.DefaultTableModel(obj, string));
		jScrollPane2.setViewportView(jTable1);

	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		String groupname = jComboBox1.getSelectedItem().toString();
		users = new Users();
		users.setNewgroupname(groupname);
		users.setLoginid(jComboBox2.getSelectedItem().toString());
		System.out.println(groupname);
		boolean b = registrationDAO.usergroupcount(users);
		if (b) {
			JOptionPane.showMessageDialog(null, "Group Changed SuccessFully",
					"Group Change", 1);
		} else {
			JOptionPane.showMessageDialog(null, "Group Fill With 3 members",
					"Group Change", 1);
		}
		File f = new File("groups");
		System.out.println(f.getAbsolutePath());
		DeleteDirectoryExample.deletemain(f.getAbsolutePath());
		
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

		int i = 0;

		Object obj[][] = new Object[10][5];
		Iterator iterator = groupchangerequest.iterator();
		while (iterator.hasNext()) {
			Users users = (Users) iterator.next();

			obj[i][0] = users.getUserid();
			obj[i][1] = users.getLoginid();
			obj[i][2] = users.getGroupname();
			obj[i][3] = users.getNewgroupname();
			obj[i][4] = users.getRequestDate();

			i++;
		}

		jTable2.setModel(new javax.swing.table.DefaultTableModel(obj,
				new String[] { "UserId", "LoginID", "OldGroupName",
						"NewGroupName", "RequestDate" }));
		jScrollPane3.setViewportView(jTable2);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		boolean b = registrationDAO.viewGroupMembers();

		fileSystemModel = new FileSystemModel(new File("groups"));
		jTree1 = new javax.swing.JTree();
		jTree1 = new JTree(fileSystemModel);
		jTree1.setEditable(true);
		jTree1.addTreeSelectionListener(new TreeSelectionListener() {
			public void valueChanged(TreeSelectionEvent event) {
				File file = (File) jTree1.getLastSelectedPathComponent();

			}
		});
		jScrollPane1.setViewportView(jTree1);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				// new GroupManagerForm().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTree jTree1;
	// End of variables declaration//GEN-END:variables

}