package com.mona.user;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import org.springframework.beans.factory.BeanFactory;

import com.mona.cloudserver.CloudServerWindow;
import com.mona.dao.DataBaseDataSource;
import com.mona.dao.RegistrationDAO;

/*
 * MainFrame.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 * 
 * @author __USER__
 */
public class MainFrame extends javax.swing.JFrame {
	RegistrationDAO registrationDAO;
	ArrayList<Users> groupchangerequest = new ArrayList<Users>();

	/** Creates new form MainFrame */
	public MainFrame() {
		BeanFactory beanFactory = new DataBaseDataSource().getDataFactory();
		registrationDAO = (RegistrationDAO) beanFactory
				.getBean("registrationDAO");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jTextField2 = new javax.swing.JTextField();
		jPasswordField2 = new javax.swing.JPasswordField();
		jPasswordField3 = new javax.swing.JPasswordField();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jComboBox1 = new javax.swing.JComboBox();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("MainFrame");

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/maxresdefault.jpg"))); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		jTabbedPane1.addTab("Welcome", jPanel1);

		jLabel6.setFont(new java.awt.Font("Arial", 1, 14));
		jLabel6.setForeground(new java.awt.Color(255, 51, 0));
		jLabel6.setText("Register Here");

		jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel7.setText("Login Name :");

		jLabel8.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel8.setText("Password :");

		jLabel9.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel9.setText("Enter Key :");

		jButton2.setText("Regsiter");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				231,
																				231,
																				231)
																		.addComponent(
																				jLabel6))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				123,
																				123,
																				123)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel3Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel8)
																										.addGap(
																												9,
																												9,
																												9))
																						.addComponent(
																								jLabel9,
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel7,
																								javax.swing.GroupLayout.Alignment.TRAILING))
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGap(
																												10,
																												10,
																												10)
																										.addComponent(
																												jPasswordField3,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												116,
																												Short.MAX_VALUE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								jPanel3Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jTextField2,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																128,
																																Short.MAX_VALUE)
																														.addComponent(
																																jPasswordField2)))))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				256,
																				256,
																				256)
																		.addComponent(
																				jButton2)))
										.addContainerGap(263, Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(59, 59, 59)
										.addComponent(jLabel6)
										.addGap(51, 51, 51)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(41, 41, 41)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(
																jPasswordField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				98,
																				98,
																				98)
																		.addComponent(
																				jButton2))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				39,
																				39,
																				39)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jPasswordField3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(97, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Registration", jPanel3);

		jLabel2.setFont(new java.awt.Font("Arial", 1, 14));
		jLabel2.setForeground(new java.awt.Color(255, 0, 51));
		jLabel2.setText("Login Here");

		jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel3.setText("Login Id :");

		jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel4.setText("Password :");

		jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel5.setText("Group Name :");

		jButton1.setText("Login");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		BeanFactory factory = new DataBaseDataSource().getDataFactory();
		RegistrationDAO registrationDAO = (RegistrationDAO) factory
				.getBean("registrationDAO");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
				registrationDAO.viewgroupNames().split(",")));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(127, 127, 127)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel4,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addComponent(jLabel5))
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				17,
																				17,
																				17)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								167,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPasswordField1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								167,
																								Short.MAX_VALUE)))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jComboBox1,
																				0,
																				166,
																				Short.MAX_VALUE)))
										.addContainerGap(253, Short.MAX_VALUE))
						.addGroup(
								jPanel2Layout.createSequentialGroup().addGap(
										240, 240, 240).addComponent(jLabel2)
										.addContainerGap(323, Short.MAX_VALUE))
						.addGroup(
								jPanel2Layout.createSequentialGroup().addGap(
										235, 235, 235).addComponent(jButton1)
										.addContainerGap(346, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(44, 44, 44)
										.addComponent(jLabel2)
										.addGap(33, 33, 33)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(44, 44, 44)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(48, 48, 48)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(37, 37, 37).addComponent(
												jButton1).addContainerGap(118,
												Short.MAX_VALUE)));

		jTabbedPane1.addTab("login", jPanel2);

		jMenu1.setText("File");

		jMenuItem1.setText("Exit");
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING,
				javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		String loginname = jTextField1.getText();
		String password = jPasswordField1.getText();
		String groupname = jComboBox1.getSelectedItem().toString();

		JPanel jpanel = new JPanel();
		if (loginname.equals("")) {
			JOptionPane.showMessageDialog(jpanel, "Please Enter LoginName");
		}
		if (password.equals("")) {
			JOptionPane.showMessageDialog(jpanel, "Please Enter Password");
		}
		if (!loginname.equals("") && !password.equals("")
				&& !groupname.equals("manager")) {
			Users users = registrationDAO.loginCheck(new Users(loginname,
					password, groupname));
			System.out.println(users.getGroupname());
			try {
				if (users.getGroupname() != null
						&& users.getLogintype().equals("user")
						|| users.getLogintype().equals("owner")) {
					UserForm welcomeUser = new UserForm(users,
							groupchangerequest);
					welcomeUser.setVisible(true);
				} else {
					JOptionPane.showMessageDialog(jpanel,
							"INVALID USER PLEASE TRY AGAIN");
				}
			} catch (Exception e) {
				System.out.println(e);
				JOptionPane.showMessageDialog(jpanel,
						"INVALID USER PLEASE TRY AGAIN");
			}

		} else {
			if (groupname.equals("manager")) {
				Users users = registrationDAO.managerLoginCheck(new Users(
						loginname, password, groupname));
				if (users.getUserid() == 100) {
					GroupManagerForm form = new GroupManagerForm(
							groupchangerequest);
					new CloudServerWindow().setVisible(true);
					form.setVisible(true);
				} else {
					JOptionPane.showMessageDialog(jpanel,
							"INVALID USER PLEASE TRY AGAIN");
				}
			} else {
				JOptionPane.showMessageDialog(jpanel,
						"INVALID USER PLEASE TRY AGAIN");
			}
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String username = jTextField2.getText();
		String password = jPasswordField2.getText();
		String userkey = jPasswordField3.getText();
		JPanel panel = new JPanel();
		if (username.trim().equals("")) {

			JOptionPane.showMessageDialog(panel, "Please Enter Loginid",
					"Error", JOptionPane.ERROR_MESSAGE);
		}
		
			boolean flag = registrationDAO.registerNewUser(new Users(username,
					password,userkey,0));
			if (flag) {
				JOptionPane.showMessageDialog(panel, "Registration Success");
			} else {
				JOptionPane.showMessageDialog(panel, "Registration Fail",
						"Error", JOptionPane.ERROR_MESSAGE);
			}

		
	}

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JPasswordField jPasswordField3;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}