package com.mona.user;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;

import org.springframework.beans.factory.BeanFactory;

import com.mona.cloudserver.CloudFile;
import com.mona.cloudserver.CloudServerWindow;
import com.mona.dao.DataBaseDataSource;
import com.mona.dao.RegistrationDAO;
import com.mona.encryption.CipherExample;
import com.mona.graph.KeySignatureGraph;
import com.mona.graph.KeyStorageGraph;
import com.mona.graph.TimeandCostGraph;
import com.mona.group.FileSystemModel;
import com.mona.key.Network;

/*
 * UserForm.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 * 
 * @author __USER__
 */
public class UserForm extends javax.swing.JFrame {
	private FileSystemModel fileSystemModel;
	RegistrationDAO registrationDAO;
	Users users;
	BeanFactory factory;
	ArrayList<Users> groupchangerequest;

	/** Creates new form UserForm */
	public UserForm(Users users, ArrayList<Users> groupchangerequest) {
		this.users = users;
		this.groupchangerequest = groupchangerequest;
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		BeanFactory factory = new DataBaseDataSource().getDataFactory();
		registrationDAO = (RegistrationDAO) factory.getBean("registrationDAO");
		setTitle("WELCOME USER");

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextArea();
		jTextField1.setText(users.getGroupsignature());
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		jComboBox1 = new javax.swing.JComboBox();
		jButton8 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuBar2 = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 204, 204));
		jPanel1.setForeground(new java.awt.Color(255, 255, 255));

		jLabel1.setBackground(new java.awt.Color(255, 204, 204));
		jLabel1.setFont(new java.awt.Font("Arial", 1, 14));
		jLabel1.setForeground(new java.awt.Color(204, 0, 0));
		jLabel1.setText("Group Signature :");

		jLabel2.setFont(new java.awt.Font("Arial", 1, 14));
		jLabel2.setForeground(new java.awt.Color(204, 0, 0));
		jLabel2.setText("Browse File :");

		jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
		jButton1.setText("Browse");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setFont(new java.awt.Font("Tahoma", 1, 11));
		jButton2.setText("Submit");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setFont(new java.awt.Font("Tahoma", 1, 11));
		jButton3.setText("View Uploaded Files");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setFont(new java.awt.Font("Tahoma", 1, 11));
		jButton4.setText("View Groups");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(55, 55, 55)
										.addComponent(
												jButton2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												119, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton4).addGap(33, 33,
												33))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(10, 10, 10)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jTextField2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												279, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton1)
										.addContainerGap())
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												140,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(335, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												465, Short.MAX_VALUE)
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												25,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												106, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton4)
														.addComponent(jButton3)
														.addComponent(jButton2))
										.addGap(33, 33, 33)));

		jPanel2.setBackground(new java.awt.Color(255, 204, 204));

		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = registrationDAO.viewFileName(users.getUserid()).split(",");

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane2.setViewportView(jList1);

		jButton5.setFont(new java.awt.Font("Tahoma", 1, 11));
		jButton5.setText("Download");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setFont(new java.awt.Font("Tahoma", 1, 11));
		jButton6.setText("Key Signature Graph");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jButton7.setFont(new java.awt.Font("Tahoma", 1, 11));
		jButton7.setText("Delete");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});
		jScrollPane3.setViewportView(jTree1);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
				registrationDAO.viewGroups().split(",")));
		jLabel3.setFont(new java.awt.Font("Arial", 1, 14));
		jLabel3.setForeground(new java.awt.Color(255, 0, 0));
		jLabel3.setText("All Uploaded Files :");

		jButton9.setFont(new java.awt.Font("Arial", 1, 12));
		jButton9.setText("Key Storage Graph");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		jButton10.setFont(new java.awt.Font("Arial", 1, 12));
		jButton10.setText("Time and Cost Graph");
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(68, 68, 68)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				271,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				171,
																				171,
																				171)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jButton5,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								244,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton6,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton7,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton9,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton10,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)))
														.addComponent(jLabel3))
										.addContainerGap(195, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(28, 28, 28)
										.addComponent(jLabel3)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				7,
																				7,
																				7)
																		.addComponent(
																				jButton5)
																		.addGap(
																				38,
																				38,
																				38)
																		.addComponent(
																				jButton7)
																		.addGap(
																				37,
																				37,
																				37)
																		.addComponent(
																				jButton6)
																		.addGap(
																				48,
																				48,
																				48)
																		.addComponent(
																				jButton9)
																		.addGap(
																				41,
																				41,
																				41)
																		.addComponent(
																				jButton10))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				322,
																				Short.MAX_VALUE)))
										.addContainerGap()));

		jPanel3.setBackground(new java.awt.Color(255, 204, 204));
		jPanel3.setForeground(new java.awt.Color(102, 255, 102));

		jScrollPane3.setViewportView(jTree1);

		jButton8.setFont(new java.awt.Font("Tahoma", 1, 11));
		jButton8.setText("Group Change");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Arial", 1, 14));
		jLabel4.setForeground(new java.awt.Color(255, 0, 0));
		jLabel4.setText("Select Group to Change :");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												165,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				78,
																				78,
																				78)
																		.addComponent(
																				jComboBox1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				126,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				60,
																				60,
																				60)
																		.addComponent(
																				jLabel4))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				91,
																				91,
																				91)
																		.addComponent(
																				jButton8)))
										.addGap(63, 63, 63)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addGap(
																				31,
																				31,
																				31)
																		.addComponent(
																				jComboBox1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				30,
																				30,
																				30)
																		.addComponent(
																				jButton8)
																		.addGap(
																				43,
																				43,
																				43))
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																234,
																Short.MAX_VALUE))));

		jMenu1.setText("File");

		jMenuItem1.setText("Exit");
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);
		jMenuBar1.add(jMenu2);

		jMenu3.setText("File");

		jMenuItem2.setText("Exit");
		jMenu3.add(jMenuItem2);

		jMenuBar2.add(jMenu3);
		jMenuBar2.add(jMenu4);

		setJMenuBar(jMenuBar2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				4,
																				4,
																				4)
																		.addComponent(
																				jPanel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jPanel3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				464,
																				Short.MAX_VALUE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jPanel2,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING,
								false).addComponent(jPanel3,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addComponent(jPanel1,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(17, Short.MAX_VALUE)));

		pack();
		jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jTable1FocusGained(evt);
			}
		});
	}// </editor-fold>

	// GEN-END:initComponents

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
		int one = registrationDAO.usercount();

		new TimeandCostGraph("TimeandCostGraph", one, one / 3);

	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		int one = registrationDAO.usercount();

		new KeyStorageGraph("KeyStorageGraph", one, one / 3);

	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		String file = jList1.getSelectedValue().toString();
		if (!file.equals("")) {
			String signature = JOptionPane.showInputDialog(null,
					"Please Enter Group Signature to Delete:",
					"Enter Signature", 1);
			boolean s;
			StringTokenizer stringTokenizer1 = new StringTokenizer(users
					.getGroupsignature().trim());
			StringTokenizer stringTokenizer2 = new StringTokenizer(signature
					.trim());

			String s1 = "";
			while (stringTokenizer1.hasMoreElements()) {
				s1 = s1 + stringTokenizer1.nextElement();
			}
			String s2 = "";
			while (stringTokenizer2.hasMoreElements()) {
				s2 = s2 + stringTokenizer2.nextElement();
			}
			if (s1.equals(s2)) {
				try {
					s = registrationDAO.deleteFile(file, signature);
					if (s) {
						JOptionPane.showMessageDialog(null, "Delete File",
								"File Deleted ", 1);
					} else {
						JOptionPane.showMessageDialog(null, "Delete File",
								"File Not Deleted", 1);
					}

				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}

			} else {
				JOptionPane.showMessageDialog(null, "Group Signature Wrong",
						"Signature Verify", 1);
			}

		} else {
			JOptionPane.showMessageDialog(null, "Please Select One File",
					"Download File", 1);
		}

	}

	
	
	private void jTable1FocusGained(java.awt.event.FocusEvent evt) {
		BeanFactory factory = new DataBaseDataSource().getDataFactory();
		 registrationDAO = (RegistrationDAO) factory
				.getBean("registrationDAO");
		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = registrationDAO.viewFileName(users.getUserid()).split(",");

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane2.setViewportView(jList1);	}
	
	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		String file = jList1.getSelectedValue().toString();
		if (!file.equals("")) {
			String deckey = JOptionPane.showInputDialog(null,
					"Please Enter KEY to Download:", "Enter Key", 1);
			String signature = jTextField1.getText().trim() + ",";
			deckey = deckey + ",";
			System.out.println(users.getGroupname());
			System.out.println(signature);
			String signature1 = null;
			String sig[] = signature.split(" ");
			for (int i = 0; i < sig.length; i++) {
				signature1 = (signature1 + sig[i].trim()).trim();
			}
			String sigg = null;
			String sig1[] = registrationDAO.viewFileSignature(
					users.getGroupname()).split(" ");
			for (int i = 0; i < sig1.length; i++) {
				sigg = (sigg + sig1[i].trim()).trim();
			}

			System.out.println(signature1);
			System.out.println(sigg);
			System.out.println(signature1.equals(sigg));

			if (signature1.equals(sigg)) {
				if (deckey.equals(registrationDAO.viewFileKey(file))) {

					String s = null;
					try {
						s = registrationDAO.downloadFile(file, deckey);
					} catch (FileNotFoundException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
					JFileChooser c = new JFileChooser();
					int x = c.showSaveDialog(null);
					if (x == JFileChooser.APPROVE_OPTION) {
						try {

							String saveFilename = null;
							String filename = new File(s).getName().toString();
							System.out.println(filename);
							String[] token = filename.split("\\.");

							if (c.getSelectedFile() != null) {
								try {
									saveFilename = c.getSelectedFile() + "."
											+ token[1];
									FileInputStream fileInputStream = new FileInputStream(
											new File(s));
									FileOutputStream fileOutputStream = new FileOutputStream(
											saveFilename);
									int data;
									while ((data = fileInputStream.read()) != -1) {
										fileOutputStream.write(data);
									}
								} catch (Exception e) {
									// TODO: handle exception
								}
							} else {
								saveFilename = new File(s).getName().toString();
							}
							System.out.println(saveFilename);
						} catch (Exception e) {
							e.printStackTrace();
						}

					}
					String deletefile = new File("upload").getAbsolutePath();
					new DeleteFile().deletemethod(deletefile);
					JOptionPane.showMessageDialog(null,
							"File Downloaded successfully", "Download File", 1);

				} else {
					JOptionPane.showMessageDialog(null, "Key not match",
							"Key Match Fail", 1);
					registrationDAO.updateRevocation(file);
				}

			} else {
				JOptionPane.showMessageDialog(null, "Signature not match",
						"Signature Fail", 1);
				registrationDAO.updateRevocation(file);
			}

		} else {
			JOptionPane.showMessageDialog(null, "Please Select File",
					"Select File", 1);

		}

	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		String groupname = jComboBox1.getSelectedItem().toString();
		if (!groupname.equals(users.getGroupname())) {

			users.setNewgroupname(groupname);
			System.out.println(groupname);
			int b = registrationDAO.groupMemberCount(groupname);
			if (b < 3) {
				users.setRequestDate(new Date());
				groupchangerequest.add(users);
				JOptionPane.showMessageDialog(null,
						"Group Change Request Sent to Group Manager",
						"Group Change", 1);
			} else {
				JOptionPane.showMessageDialog(null,
						"Group Already Fill With 3 members", "Group Change", 1);
			}
			// System.out.println("file deleted ddddd" + delete);
			// new GroupMemberchange(users).setVisible(true);

		} else {
			JOptionPane.showMessageDialog(null, "You are in same group",
					"Group Change", 1);
		}
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		jPanel3.enable(true);

		boolean b = registrationDAO.viewGroupMembers();

		fileSystemModel = new FileSystemModel(new File("groups"));
		jTree1 = new javax.swing.JTree();
		jTree1 = new JTree(fileSystemModel);
		jTree1.setEditable(true);
		jTree1.addTreeSelectionListener(new TreeSelectionListener() {
			public void valueChanged(TreeSelectionEvent event) {
				File file = (File) jTree1.getLastSelectedPathComponent();

			}
		});
		jScrollPane3.setViewportView(jTree1);
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		BeanFactory factory = new DataBaseDataSource().getDataFactory();
		registrationDAO = (RegistrationDAO) factory.getBean("registrationDAO");
		Object obj[][] = registrationDAO.viewCloudFiles(users.getUserid());
		Object string[] = registrationDAO.viewCloudMetaData();
		new CloudServerWindow().setVisible(true);

		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = registrationDAO.viewFileName(users.getUserid())
					.split(",");

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String ipString = JOptionPane.showInputDialog(null,
				"Please Enter CLOUD IPADDRESS:", "CLOUD IPADDRESS", 1);
		
		String userkey = JOptionPane.showInputDialog(null,
				"Please Enter USER KEY:", "USER KEY", 1);

		String addr = "";
		try {
			addr = InetAddress.getLocalHost().getHostAddress();
		} catch (UnknownHostException e) {
			e.printStackTrace();
		}
		if (addr.equals(ipString) && userkey.equals(users.getUserkey())) {
			String file = jTextField2.getText();

			CloudFile cloudFile = new CloudFile();
			cloudFile.setGroupname(users.getGroupname());
			cloudFile.setLoginid(users.getLoginid());
			cloudFile.setGroupsignature(users.getGroupsignature());
			cloudFile.setChangegroupsignature(users.getGroupsignature());
			cloudFile.setFilename(new File(file).getName());

			String pubKey = new Network().getKey();
			cloudFile.setPubKey(pubKey);
			try {
				String fileextension[] = file.split("\\.");
				cloudFile.setFiletype(fileextension[fileextension.length - 1]);
			} catch (Exception e) {
				cloudFile.setFiletype(".txt");
			}
			String enc = null;
			try {
				enc = new CipherExample().encrypt(cloudFile.getPubKey(), file);
			} catch (Throwable e) {
				// TODO: handle exception
			}
			cloudFile.setEncryptfiledata(new File(enc));
			BeanFactory beanFactory = new DataBaseDataSource().getDataFactory();
			RegistrationDAO registrationDAO = (RegistrationDAO) beanFactory
					.getBean("registrationDAO");

			boolean flag = registrationDAO.uploadCloudFile(cloudFile);
			
			
			if (flag) {
				JOptionPane.showMessageDialog(null,
						"FILE UPLOADED SUCCESSFULLY", "FILE UPLOAD", 1);
			} else {
				JOptionPane.showMessageDialog(null, "FILE UPLOADED",
						"FILE UPLOAD", 1);
			}

		} else {
			JOptionPane.showMessageDialog(null,
					"IPADDRESS CLOUD NOT FIND (or) user key not match PLEASE TRY AGAIN",
					"CLOUD IPADDRESS (OR) USER KEY", 1);
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		browse();
	}

	private void browse() {
		// TODO Auto-generated method stub
		JFileChooser jfr = new JFileChooser();
		int check = jfr.showOpenDialog(this);
		try {
			if (check == JFileChooser.APPROVE_OPTION) {

				String path = jfr.getSelectedFile().getPath();

				jTextField2.setText(path);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		int one = registrationDAO.usercount();

		new KeySignatureGraph("KeySignatureGraph", one, one / 3);
		// ChartPanel.viewGraph(one, two);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				// new UserForm().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JList jList1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTextArea jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTree jTree1;
	// End of variables declaration//GEN-END:variables

}