/*
 * ViewGroupMembers.java
 *
 * Created on __DATE__, __TIME__
 */

package com.mona.group;


import org.springframework.beans.factory.BeanFactory;

import com.mona.dao.DataBaseDataSource;
import com.mona.dao.RegistrationDAO;

/**
 *
 * @author  __USER__
 */
public class ViewGroupMembers extends javax.swing.JFrame {

	/** Creates new form ViewGroupMembers */
	public ViewGroupMembers() {
		
		BeanFactory beanFactory=new DataBaseDataSource().getDataFactory();
		RegistrationDAO registrationDAO=(RegistrationDAO)beanFactory.getBean("registrationDAO");
		
		boolean b=registrationDAO.viewGroupMembers();
		
		
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		setTitle("ViewGroups");
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 757,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 504,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ViewGroupMembers().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	// End of variables declaration//GEN-END:variables

}